### ISSUE TITLE
Looks like bug - `b('').join` vs `b''.join`

### ISSUE THREAD

**Issue by lefan** [OndrejHome/ansible.pcs-modules-2#15]
Hi @OndrejHome.

I am not a python dev, but it looks like bug in this line:
https://github.com/OndrejHome/ansible.pcs-modules-2/blob/7d12f5e9758e43242b2e09c338923d61276db331/library/pcs_resource.py#L144
and L146 
Maybe something like `to_native(b''.join(n...`

**Comment by OndrejHome** [comment]
Hi @lefan,
Yes, it fails why I try it with all versions of python I have on computer (2.7, 3.5, 3.6). I would say that it was working before when I was adding the changes to make printing there only when we have a `to_native` function available. I could remember it worked for me at that time, but now it doesn't :)

So yes, this is something for fixing. Let me take care of it and thank you a lot for finding this!
I really need to automate somehow testing of the code to catch this kind of bugs.

**Comment by OndrejHome** [comment]
I have merged the fix for this into `master` (v15). I have the #16 opened to track the cases where my lack of full testing resulted in problems like this and will try to address it there over time.
In case that current `master` has still same/similar issue as seen here on any of your setups please let me know. If there is no problem feel free to close this issue or I will close it in 1-2 weeks from now if there is no response considering that there was nothing problematic.

Thank you once again for reporting this issue!
