### ISSUE TITLE
pcs_resource is unable to push CIB during 

### ISSUE THREAD

**Issue by YanChii** [OndrejHome/ansible.pcs-modules-2#39]
Hi,

I'm [trying to create a multistate resource](https://github.com/YanChii/ansible-role-postgres-ha/blob/dbad41bc0a6f97b9154a29a8663686fe8ef9639f/tasks/paf.yml#L57) and it's failing with 
```
fatal: [pgha1]: FAILED! => {"changed": false, "error": "Error: Unable to push to the CIB because pushed configuration is older than existing one. If you are sure you want to push this configuration, try to use --config to replace only configuration part instead of whole CIB. Otherwise get current configuration by running command 'pcs cluster cib' and update that.\n", "msg": "Failed to push updated configuration for multistate resource to cluster using command 'pcs cluster cib-push  /tmp/tmpigjvq45_'. Creation of multistate resource was rolled back. You can retry this task with 'force_resource_update=true' to see if that helps.", "output": ""}
```
However, it has helped to add `--config` [here ](https://github.com/OndrejHome/ansible.pcs-modules-2/blob/c23d25be1edd4e39b91bf3004bbe94e88cc3f964/library/pcs_resource.py#L366). I'm creating an issue to ask if this is the proper way of handling it.

Thx.

Jan

**Comment by OndrejHome** [comment]
Hello Jan,

Thank you for using the modules and for your description.

The part where this produces error is second step in 2 steps process for creating multistate resource:
- step 1 create multistate resource with all options as specified with specified or default child_name
- step 2 rename the created resource in cluster to match `name`+`child_name` requested in module - this here because of way how pcs dropped ability to specify name from pcs-0.10 and therefore the CIB update became the only solution

In second step module tries to get fresh configuration of cluster at https://github.com/OndrejHome/ansible.pcs-modules-2/blob/c23d25be1edd4e39b91bf3004bbe94e88cc3f964/library/pcs_resource.py#L350 but it is still possible that some things can change in CIB which usually triggers similar message to one you have seen.

However as stated in error message the `force_resource_update=true` option is suggested as possible solution here. This option adds `scope=resources` https://github.com/OndrejHome/ansible.pcs-modules-2/blob/c23d25be1edd4e39b91bf3004bbe94e88cc3f964/library/pcs_resource.py#L365 which is effectively `--config` but only over resources part of configuration, therefore it should have same effect here as `--config`.

1. I can see that you have `force_resource_update=true` option commented out. Was task working well when option was used or same error was reported?
2. Which OS and cluster versions are you using? (`pcs --version`, `uname -a`)

**Comment by OndrejHome** [comment]
Hi @YanChii,
Force be with you when needed :)
But in any case I have added the earlier mentioned change to code that will apply the force when master/promotable resource is being handled automatically. Change is now in `master` without any new tag - once there are more changes or little bit latter this month I plan to release release new version. Until then you can use the latest commit from `master` to get new improved behaviour. Also the documentation was a bit improved to describe better the situation when the option can be used.

Thank you again for initiating the discussion here and please let me know if there is anything left to clear up or explain. If not feel free to close this issue or if I will not hear from you for some time (lets say more than 2 weeks) I will close it myself as I believe that this should be now addressed.

**Comment by YanChii** [comment]
Thank you.
I believe we can close it now. I can reopen if I hit anything related to this.
Either way, I've explicitly set `force` in the role and now it does what it should.
Thanks.
Jan
